/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.90
 * Generated at: 2024-08-01 00:12:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.model.RecPolicyDAO;
import com.model.UserDTO;
import com.model.UserDAO;
import com.model.PolicyDAO;
import com.model.PolicyDTO;
import java.util.List;

public final class policyView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("com.model.RecPolicyDAO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.model.UserDAO");
    _jspx_imports_classes.add("com.model.PolicyDAO");
    _jspx_imports_classes.add("com.model.UserDTO");
    _jspx_imports_classes.add("com.model.PolicyDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>Blue Wave</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/policyViewST.css\" />\r\n");
      out.write("    <style>\r\n");
      out.write("        /* 정책 정보 테이블 스타일 */\r\n");
      out.write("        .table_wrap {\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .common_table01.type2 {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .common_table01.type2 li {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            border-bottom: 1px solid #e0e0e0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .common_table01.type2 li:last-child {\r\n");
      out.write("            border-bottom: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .list_tit, .list_cont {\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            line-height: 1.5;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .list_tit {\r\n");
      out.write("            width: 30%;\r\n");
      out.write("            background-color: #f5f5f5;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            border-right: 1px solid #e0e0e0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .list_cont {\r\n");
      out.write("            width: 70%;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* 섹션 제목 스타일 */\r\n");
      out.write("        .tbl-header {\r\n");
      out.write("            margin-top: 30px;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("            border-bottom: 2px solid #333;\r\n");
      out.write("            padding-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .h3-tit {\r\n");
      out.write("            font-size: 1.2em;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* 정책 이름 스타일 */\r\n");
      out.write("        .doc_tit01.type2 {\r\n");
      out.write("            font-size: 1.8em;\r\n");
      out.write("            color: #0066cc;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            padding-bottom: 15px;\r\n");
      out.write("            border-bottom: 2px solid #0066cc;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* 컨테이너 스타일 수정 */\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 1000px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* 반응형 디자인 */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .common_table01.type2 li {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("            }\r\n");
      out.write("        \r\n");
      out.write("            .list_tit, .list_cont {\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                border-right: none;\r\n");
      out.write("            }\r\n");
      out.write("        \r\n");
      out.write("            .list_tit {\r\n");
      out.write("                border-bottom: 1px solid #e0e0e0;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

    UserDTO info = (UserDTO)session.getAttribute("user");

      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <nav>\r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("            <a href=\"main.jsp\"> <img src=\"image/Blue Wave.png\" alt=\"Blue Wave Logo\"> </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("</header>\r\n");
    
    String policyId = request.getParameter("policyId");
    PolicyDAO policyDAO = new PolicyDAO();
    PolicyDTO policy = null;

    if (policyId != null && !policyId.isEmpty()) {
        policy = policyDAO.getPolicyById(policyId);
    }

    if (policy != null) {

      out.write('\r');
      out.write('\n');

    String category = "-";
    if (policy.getPOLICY_FIELD_CODE().equals("23010") || policy.getPOLICY_FIELD_CODE().equals("023010")) {
        category = "일자리 분야";
    } else if (policy.getPOLICY_FIELD_CODE().equals("23020") || policy.getPOLICY_FIELD_CODE().equals("023020")) {
        category = "주거 분야";
    } else if (policy.getPOLICY_FIELD_CODE().equals("23030") || policy.getPOLICY_FIELD_CODE().equals("023030")) {
        category = "교육 분야";
    } else if (policy.getPOLICY_FIELD_CODE().equals("23040") || policy.getPOLICY_FIELD_CODE().equals("023040")) {
        category = "복지.문화 분야";
    } else if (policy.getPOLICY_FIELD_CODE().equals("23050") || policy.getPOLICY_FIELD_CODE().equals("023050")) {
        category = "참여.권리 분야";
    }

      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <h2 class=\"doc_tit01 type2\">");
      out.print(policy.getPOLICY_NAME());
      out.write("</h2>\r\n");
      out.write("    <div class=\"tbl-header\">\r\n");
      out.write("        <h3 class=\"h3-tit\">정책 정보 요약</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"table_wrap\">\r\n");
      out.write("        <ul class=\"common_table01 type2\">\r\n");
      out.write("            ");
 if (policy.getPOLICY_ID() != null) { 
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"list_tit\">정책 번호</div>\r\n");
      out.write("                <div class=\"list_cont\">");
      out.print( policy.getPOLICY_ID() );
      out.write("</div>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if (category != null && !category.equals("-")) { 
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"list_tit\">정책 분야</div>\r\n");
      out.write("                <div class=\"list_cont\">");
      out.print( category );
      out.write("</div>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if (policy.getSUPPORT_CONTENT() != null) { 
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"list_tit\">지원 내용</div>\r\n");
      out.write("                <div class=\"list_cont\">");
      out.print( policy.getSUPPORT_CONTENT() );
      out.write("</div>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if (policy.getOPERATION_PERIOD() != null) { 
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"list_tit\">사업 운영 기간</div>\r\n");
      out.write("                <div class=\"list_cont\">");
      out.print( policy.getOPERATION_PERIOD() );
      out.write("</div>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if (policy.getAPPLICATION_PERIOD() != null) { 
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"list_tit\">사업 신청 기간</div>\r\n");
      out.write("                <div class=\"list_cont\">");
      out.print( policy.getAPPLICATION_PERIOD() );
      out.write("</div>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if (policy.getSUPPORT_SCALE() != null) { 
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"list_tit\">지원 규모(명)</div>\r\n");
      out.write("                <div class=\"list_cont\">");
      out.print( policy.getSUPPORT_SCALE() );
      out.write("</div>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if (policy.getETC() != null) { 
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"list_tit\">비고</div>\r\n");
      out.write("                <div class=\"list_cont\">");
      out.print( policy.getETC() );
      out.write("</div>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"tbl-header\">\r\n");
      out.write("        <h3 class=\"h3-tit\">신청자격</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"table_wrap\">\r\n");
      out.write("        <ul class=\"common_table01 type2\">\r\n");
      out.write("            ");
 if (policy.getAGE_INFO() != null) { 
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"list_tit\">연령</div>\r\n");
      out.write("                <div class=\"list_cont\">");
      out.print( policy.getAGE_INFO() );
      out.write("</div>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if (policy.getRESIDENCE_INCOME_CONDITION() != null) { 
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"list_tit\">거주지 및 소득</div>\r\n");
      out.write("                <div class=\"list_cont\">");
      out.print( policy.getRESIDENCE_INCOME_CONDITION() );
      out.write("</div>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if (policy.getPOLICY_DESC() != null) { 
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"list_tit\">학력</div>\r\n");
      out.write("                <div class=\"list_cont\">");
      out.print( policy.getPOLICY_DESC() );
      out.write("</div>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if (policy.getSUPPORT_CONTENT() != null) { 
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"list_tit\">전공</div>\r\n");
      out.write("                <div class=\"list_cont\">");
      out.print( policy.getSUPPORT_CONTENT() );
      out.write("</div>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if (policy.getAPPLICATION_PROCESS() != null) { 
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"list_tit\">취업 상태</div>\r\n");
      out.write("                <div class=\"list_cont\">");
      out.print( policy.getAPPLICATION_PROCESS() );
      out.write("</div>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if (policy.getAPPLICATION_PROCEDURE() != null) { 
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"list_tit\">특화 분야</div>\r\n");
      out.write("                <div class=\"list_cont\">");
      out.print( policy.getAPPLICATION_PROCEDURE() );
      out.write("</div>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if (policy.getSUPPORT_SCALE() != null) { 
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"list_tit\">추가 단서 사항</div>\r\n");
      out.write("                <div class=\"list_cont\">");
      out.print( policy.getSUPPORT_SCALE() );
      out.write("</div>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"tbl-header\">\r\n");
      out.write("        <h3 class=\"h3-tit\">신청 절차</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"table_wrap\">\r\n");
      out.write("        <ul class=\"common_table01 type2\">\r\n");
      out.write("            ");
 if (policy.getAPPLICATION_PROCEDURE() != null) { 
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"list_tit\">신청 절차</div>\r\n");
      out.write("                <div class=\"list_cont\">");
      out.print( policy.getAPPLICATION_PROCEDURE() );
      out.write("</div>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if (policy.getEVALUATION_AND_ANNOUNCEMENT() != null) { 
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"list_tit\">심사 및 발표</div>\r\n");
      out.write("                <div class=\"list_cont\">");
      out.print( policy.getEVALUATION_AND_ANNOUNCEMENT() );
      out.write("</div>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if (policy.getAPPLICATION_SITE_URL() != null && !policy.getAPPLICATION_SITE_URL().isEmpty()) { 
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"list_tit\">신청 사이트</div>\r\n");
      out.write("                <div class=\"list_cont\" style=\"word-break: break-all\">\r\n");
      out.write("                    <a href=\"");
      out.print( policy.getAPPLICATION_SITE_URL() );
      out.write("\" target=\"_blank\">\r\n");
      out.write("                        ");
      out.print( policy.getAPPLICATION_SITE_URL() );
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if (policy.getSUBMISSION_DOCUMENTS() != null) { 
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"list_tit\">제출 서류</div>\r\n");
      out.write("                <div class=\"list_cont\">");
      out.print( policy.getSUBMISSION_DOCUMENTS() );
      out.write("</div>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"tbl-header\">\r\n");
      out.write("        <h3 class=\"h3-tit\">기타</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"table_wrap\">\r\n");
      out.write("        <ul class=\"common_table01 type2\">\r\n");
      out.write("            ");
 if (policy.getETC() != null) { 
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"list_tit\">기타 유익 정보</div>\r\n");
      out.write("                <div class=\"list_cont\">");
      out.print( policy.getETC() );
      out.write("</div>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if (policy.getMAIN_DEPARTMENT_NAME() != null) { 
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"list_tit\">주관 기관</div>\r\n");
      out.write("                <div class=\"list_cont\">");
      out.print( policy.getMAIN_DEPARTMENT_NAME() );
      out.write("</div>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if (policy.getOPERATING_INSTITUTION_NAME() != null) { 
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"list_tit\">운영 기관</div>\r\n");
      out.write("                <div class=\"list_cont\">");
      out.print( policy.getOPERATING_INSTITUTION_NAME() );
      out.write("</div>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if (policy.getREFERENCE_SITE_URL1() != null && !policy.getREFERENCE_SITE_URL1().isEmpty()) { 
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"list_tit\">사업관련 참고 사이트 1</div>\r\n");
      out.write("                <div class=\"list_cont\" style=\"word-break: break-all\">\r\n");
      out.write("                    <a href=\"");
      out.print( policy.getREFERENCE_SITE_URL1() );
      out.write("\" target=\"_blank\">\r\n");
      out.write("                        ");
      out.print( policy.getREFERENCE_SITE_URL1() );
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if (policy.getREFERENCE_SITE_URL2() != null && !policy.getREFERENCE_SITE_URL2().isEmpty()) { 
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"list_tit\">사업관련 참고 사이트 2</div>\r\n");
      out.write("                <div class=\"list_cont\" style=\"word-break: break-all\">\r\n");
      out.write("                    <a href=\"");
      out.print( policy.getREFERENCE_SITE_URL2() );
      out.write("\" target=\"_blank\">\r\n");
      out.write("                        ");
      out.print( policy.getREFERENCE_SITE_URL2() );
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");

    } else {

      out.write("\r\n");
      out.write("<p>해당 정책을 찾을 수 없습니다.</p>\r\n");

    }

      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    <div class=\"footer-container\">\r\n");
      out.write("        <img src=\"image/Blue Wave.png\" alt=\"Logo\" class=\"footer-logo\" />\r\n");
      out.write("        <nav class=\"footer-nav\">\r\n");
      out.write("            <a href=\"#\">팀 소개</a>\r\n");
      out.write("            <a href=\"#\">이용약관</a>\r\n");
      out.write("            <a href=\"#\">개인정보처리방침</a>\r\n");
      out.write("            <a href=\"#\">시스템 문의</a>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
